elastos/Elastos.ELA

- core/auxpow/auxpow.go
- net/servers/interfaces.go
1. fix generateAuxBlock return nil when there is no transaction.
2. change ChainId to 6.
> fix CreateAuxBlock method and change the chain id

- config.json
- consensus/pow/pow.go
- core/auxpow/auxpow.go
- core/ledger/txValidator.go
- core/transaction/payload/SideMining.go
- core/transaction/transaction.go
- net/servers/common.go
- net/servers/httpjsonrpc/server.go
- net/servers/interfaces.go
1. change chain id to 6
2. fixe 'generateAuxBlock' return nil when there is no transaction
3. It  should be double hash when checking merkle branch
4. adjust AuxBlock bytes order
5. reverse AuxBlock hash when multiple auxiliary chains mining
> fix merge mining bugs

- glide.lock
- net/servers/httpjsonrpc/server.go
- net/servers/httpwebsocket/server.go
- net/servers/interfaces.go
1. add bitcoin like json rpc interfaces.
2. change the architecture of json rpc server.
3. modify some error codes in json rpc server.
> some change on json rpc interfaces

- servers/httpjsonrpc/server.go
- servers/interfaces.go
add second parameter `decoded` to GetRawTransaction() method according to BTC RPC protocol
> add second parameter to GetRawTransaction() method

- pow/pow.go
Repacking block per 15 seconds for packing the mining transaction of a side chain regularly.
> repacking block per 15 seconds

- node/node.go
- servers/httpjsonrpc/server.go
- servers/interfaces.go
fix nil pointer error when GetTransactionInfo() pass nil header
> fix nil pointer error when GetTransactionInfo() pass nil header

- README.md
- docs/Elastos_Wallet_Development_Environment_CN.md
- docs/Elastos_Wallet_Development_Environment_Deployment_CN.md
- docs/Elastos_Wallet_Node_API_CN.md
1.Node API sample;
2.The Elastos Wallet environment document;
3.How to delopy the environment of Elastos Wallet;
> add some documents about Elastos Wallet

- blockchain/txpool.go
- blockchain/validation.go
- core/payloadissuetoken.go
- core/payloadtransfercrosschainasset.go
- servers/common.go
- servers/interfaces.go
1.Change cross chain payload for calculating fee.
2.Fix bug: withdraw transaction can not transfer to account.
> Modify for cross chain

- common/config/config.go
- core/ledger/ledger.go
Reverts elastos/Elastos.ELA#72
> Revert "adjust foundation address to be configurable"

- .gitignore
- blockchain/blockvalidator.go
- blockchain/chaindata.go
- blockchain/chainstore.go
- blockchain/chainstore_test.go
- blockchain/dataentryprefix.go
- blockchain/ledgerstore.go
- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- errors/errcode.go
1. check for duplicate UTXO inputs in a block
2. check for duplicate sidechain Tx in a block
3. check for duplicate sidechain Tx in a transaction
4. check for a double spend of sidechain Tx in the ledge
> check for double spend in the ledge

- servers/httpjsonrpc/server.go
Added the missing parameter processing logic on sendrawtransaction
> missing parameter processing on sendrawtransaction

- blockchain/txpool.go
- blockchain/txpool_test.go
- docs/jsonrpc_apis.md
- errors/errcode.go
- main.go
- node/handlerbase.go
- node/handlereip001.go
- node/infoupdate.go
- node/node.go
- node/nodemap.go
- pow/pow.go
- protocol/protocol.go
- servers/common.go
- servers/httpjsonrpc/server.go
- servers/interfaces.go
- servers/params.go
now the txn pool will delete pool's txns which have the same utxos with txns in blocks.
> change the rule of cleaning txn pool when a block is persisted.

- blockchain/txpool.go
- blockchain/txpool_test.go
…n lists, to keep synchronized.
> transaction pool bug

- blockchain/txpool.go
- pow/pow.go
> check transaction context when generate block and remove transactions

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- blockchain/validation.go
- blockchain/validation_test.go
The sort programs method got crash because of an invalid opcode in program code. We check the transaction programs before it can be sorted.
> implement CheckAttributeProgram(*Transaction) method to fix issue #182

- core/ledger/block.go
- core/transaction/txAttribute.go
1. add new txAttribute type
2. add error handling in block deserializing codes.
> compatibility fix

- node/node.go
- node/node_state.go
- node/nodemap.go
- protocol/protocol.go
Dump local node state information to log per 5 minutes like
> dump ndoe status information into log per 5 minute

- node/handlerbase.go
- node/handlereip001.go
- node/handlerv0.go
- node/handshakedqueue.go
- node/infoupdate.go
- node/knowaddrlist.go
- node/link.go
- node/node.go
- node/nodemap.go
- protocol/protocol.go
- servers/interfaces.go
Some minor fix and implement keep internal connections not less than MinConnectionCount.
> Keep internal connections

- docs/jsonrpc_apis.md
- main.go
- servers/common.go
- servers/httpnodeinfo/server.go
- servers/httprestful/server.go
- servers/interfaces.go
Improve GetNodeState() interface in RPC to return more information like neighbor nodes.
Add GetNodeState() to RESTful interface as the same in RPC.
Response example:
{
"Desc": "Success",
"Error": 0,
"Result": {
"Compile": "v0.1.1-50-gcd97-dirty",
"ID": 5264835935806907010,
"HexID": "0x49107463aa7b6282",
"Height": 168739,
"Version": 0,
"Services": 4,
"Relay": true,
"TxnCnt": 3,
"RxTxnCnt": 1,
"Port": 20338,
"PRCPort": 20336,
"RestPort": 20334,
"WSPort": 20335,
"OpenPort": 20866,
"OpenService": true,
"Neighbors": [
{
"ID": 474550124097821846,
"HexID": "0x695f0d2d6f7dc96",
"Height": 168739,
"Services": 4,
"Relay": true,
"External": false,
"State": "ESTABLISH",
"NetAddress": "35.177.88.106:20866"
},
{
"ID": 2036552338286151341,
"HexID": "0x1c43498fc20986ad",
"Height": 168739,
"Services": 4, …
> Get node state

- blockchain/txpool.go
- node/handlerbase.go
- node/infoupdate.go
- node/link.go
- node/node.go
- pow/pow.go
1. Change idleTimeout
2. Add some debug log
> change idleTimeout

- common/config/template.go
- servers/httpjsonrpc/server.go
> rpc add localhost

- pow/service.go
- servers/httpjsonrpc/server.go
mining and add block is now in the same go routine. Mining request value and adding-block send value, so this go routine will be blocked. And mining cannot continue.
> remove pow persist block notify

- .travis.yml
disable tests temporarily until all tests passed later
> disable unit and whitebox test temporarily

- config.go
- main.go
- version/blocks/blockv0.go
Fixed the foundation address to be initialized only when a configuration iterm exist.
> fix foundation address initialization

- p2p/server/server.go
Network address filter not initialized when create the server peer, so the network addresses can not be added into AddrManager and relayed to other peers.
> fix network address filter not working issue

- blockchain/blockchain.go
- dpos/arbitrator.go
- dpos/manager/dposmanager.go
- dpos/network.go
- dpos/state/arbitrators.go
- dpos/state/state.go
- version/blocks/blockv0.go
2.if arbiter not in direct peers list not connect to others
> change to dpos arbiters when received block equal dpos height-1

- version/version.go
If set height versions less than 4 can repeat this error
> fix log package import error

- blockchain/chainstore.go
Seems like the resources has not been released .
> Release resources

- servers/httpwebsocket/server.go
> Fix web socket request param data coherent problem

- blockchain/chaindata.go
- blockchain/chainstore.go
https://github.com/elastos/Elastos.ELA.TestManagement/issues/16
> Fix persist UTXOs error issue

- dpos/manager/viewchangescountdown.go
- dpos/state/arbitrators.go
> fix inactive arbiter when timeout after update next arbiters

- cmd/wallet/common.go
- cmd/wallet/txbuilder.go
- servers/interfaces.go
1. fix cli no-change bug
2. use getUTXOsByAmount interface instead of listunspent when creating inputs
> fix cli no-change bug

- dpos/state/arbitrators.go
Improve code cleanup duplicate code
> Improve code cleanup duplicate code

- .gitlab-ci.yml
> Add auto DevOps ci/cd for PaaS platforms

- account/fileStore.go
- cmd/common/common.go
- cmd/wallet/common.go
- dpos/p2p/addrmgr/addrmanager.go
- p2p/addrmgr/addrmanager.go
- utils/elalog/filewriter.go
> Improve file permissions security

- .gitlab-ci.yml
> Fix project name and go path issus

- .gitlab-ci.yml
> Add coverage check for ci

- README.md
> change Build Status to travis.com

- .header.cfg
- blockchain/mediantime.go
- blockchain/mediantime_test.go
- crypto/ecies/ecies.go
- crypto/ecies/ecies_test.go
- crypto/ecies/params.go
- dpos/dtime/mediantime.go
- dpos/dtime/mediantime_test.go
- dpos/p2p/peer/peer_test.go
- elanet/bloom/murmurhash3.go
- p2p/peer/peer_test.go
- p2p/server/upnp.go
> Add referenced third party copyright information

- blockchain/txvalidator_test.go
- cmd/script/api/api.go
- dpos/state/arbitrators.go
- dpos/state/arbitrators_test.go
- dpos/state/heightversion_test.go
- main.go
edit based on https://github.com/elastos/Elastos.ELA/pull/1035
> Remove GetBestBlock() parameter from Arbitrators

- core/checkpoint/channels.go
- core/checkpoint/channels_test.go
- core/checkpoint/manager.go
- core/checkpoint/manager_test.go
- cr/state/checkpoint.go
- dpos/state/keyframe.go
> Unify the lincesen format

- docs/jsonrpc_apis.md
- servers/httpjsonrpc/server.go
- servers/interfaces.go
- test/transaction/activate_producer_tx.lua
- test/transaction/cancel_producer_tx.lua
- test/transaction/unregister_cr_tx.lua
1, unregister_cr, cancel_producer and active_producer lua script support pass parameters
2, cr api interface chg did to did address
>  unregister_cr, cancel_producer and active_producer lua script support pass parameters

- blockchain/difficulty_test.go
> Add license header

- glide.yaml
> Fixed glide bug

- cmd/script/api/outputtype.go
- cmd/script/script.go
> CR: Fixed cr votes string to number issus

- test/transaction/vote_cr_tx.lua
> CR: Fixed candidates and candidateVotes number inconsistent

- .gitignore
- Makefile
- blockchain/txvalidator.go
> CR: Fixed log display error

- .drone.yml
- blockchain/txvalidator_test.go
- cr/state/state.go
> CR: Fixed duplicate records for cr re-registration

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
> CR: Fixed register cr log bug

- .drone.yml
- docker/Dockerfile
> Docker: Refactoring docker images

- blockchain/chainio.go
- blockchain/upgrade.go
- blockchain/utxocache.go
- blockchain/utxocache_test.go
- blockchain/weight.go
- database/doc.go
- database/driver.go
- database/driver_test.go
- database/error.go
- database/error_test.go
- database/export_test.go
- database/ffldb/blockio.go
- database/ffldb/db.go
- database/ffldb/dbcache.go
- database/ffldb/doc.go
- database/ffldb/driver.go
- database/ffldb/ldbtreapiter.go
- database/ffldb/reconcile.go
- database/interface.go
- database/internal/treap/common.go
- database/internal/treap/common_test.go
- database/internal/treap/doc.go
- database/internal/treap/immutable.go
- database/internal/treap/immutable_test.go
- database/internal/treap/mutable.go
- database/internal/treap/mutable_test.go
- database/internal/treap/treapiter.go
- database/internal/treap/treapiter_test.go
- docker/Dockerfile
> Add license

- Makefile
- docker/Dockerfile
> Fix Makefile version bug

- LICENSE
> Fix LICENSE error

- database/doc.go
- database/driver.go
- database/driver_test.go
- database/error.go
- database/error_test.go
- database/export_test.go
- database/ffldb/blockio.go
- database/ffldb/db.go
- database/ffldb/dbcache.go
- database/ffldb/doc.go
- database/ffldb/driver.go
- database/ffldb/ldbtreapiter.go
- database/ffldb/reconcile.go
- database/interface.go
- database/internal/treap/common.go
- database/internal/treap/common_test.go
- database/internal/treap/doc.go
- database/internal/treap/immutable.go
- database/internal/treap/immutable_test.go
- database/internal/treap/mutable.go
- database/internal/treap/mutable_test.go
- database/internal/treap/treapiter.go
- database/internal/treap/treapiter_test.go
> Removes duplicate license

- blockchain/txvalidator.go
> Fixed CheckVoteOutputs print log incorrect

- .drone.yml
- Makefile
- docker/Dockerfile
- docker/docker-compose.yml
Depended https://github.com/elastos/Elastos.ELA/pull/1229
> Support docker compose

- docker/docker-compose.yml
> Docker-compose default latest image

- mempool/txpool.go
- mempool/txpool_test.go
> check duplicate nickname in txpool

- blockchain/blockvalidator.go
- blockchain/blockvalidator_test.go
- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- cmd/script/api/outputtype.go
- cmd/script/api/payloadtype.go
- core/checkpoint/manager.go
- core/types/payload/unregistercr.go
- core/types/payload/unregistercr_test.go
- cr/state/candidate_test.go
- cr/state/keyframe_test.go
- cr/state/state.go
- cr/state/state_test.go
- dpos/state/checkpoint.go
- mempool/txpool.go
cr vote target from code to did ok
> change cr voting key from code to did

- Makefile
- blockchain/blockvalidator.go
> Fixed block timestamp is not after expected in docker

- .drone.yml
- Makefile
> Add cr case framework for ci

- cmd/script/api/outputtype.go
- mempool/txpool.go
- mempool/txpool_test.go
> fix bugs of release_v0.4.0

- errors/jsonformat.go
> Use switch-type format

- blockchain/blockchain.go
- blockchain/chaindata.go
- blockchain/chaindata_test.go
- blockchain/chainstore.go
- blockchain/chainstore_test.go
- blockchain/chainstoreffldb.go
- blockchain/indexers/common.go
- blockchain/indexers/manager.go
- blockchain/indexers/tx3index.go
- blockchain/indexers/tx3index_test.go
- blockchain/indexers/txindex.go
- blockchain/indexers/unspentindex.go
- blockchain/indexers/unspentindex_test.go
- blockchain/indexers/utxoindex.go
- blockchain/indexers/utxoindex_test.go
- blockchain/ledgerstore.go
- blockchain/txvalidator.go
- core/types/utxo.go
- cr/state/committee.go
- main.go
- servers/common.go
- servers/interfaces.go
- wallet/wallet.go
implement unspent、utxo and tx3 store with ffldb bucket
> Database profile

- blockchain/txvalidator.go
> Allow proposals to track other states that can be withdraw

- .gitignore
- blockchain/txvalidator.go
- cmd/common/flags.go
- cmd/script/api/txtype.go
- common/config/config.go
- common/config/params.go
- cr/state/state.go
- settings.go
> The CRDepositLockupBlocks parameter ported to config file

- blockchain/txvalidator_test.go
- cmd/script/api/payloadtype.go
- cmd/script/api/proposal.go
- cmd/script/script.go
- core/types/payload/crcproposal.go
- core/types/payload/crcproposaltracking.go
- core/types/transaction_test.go
- test/transaction/crc_proposal_tracking.lua
- test/transaction/crc_proposal_tx.lua
> Add opinion hash on the transaction for crproposal

- cmd/script/api/payloadtype.go
> Fixed crSig error signature when key is empty.

- cr/state/committee.go
- servers/httpjsonrpc/server.go
- servers/interfaces.go
> Rpc add listsecretary and fixed member refundable  status

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- common/serialize.go
- core/types/payload/crcproposal.go
> Adjust the proposal type to include a category data field

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- cmd/script/api/payloadtype.go
- cmd/wallet/txbuilder.go
- core/types/payload/crcproposal.go
- core/types/payload/crcproposaltracking.go
- core/types/payload/crcproposalwithdraw.go
- core/types/transaction_test.go
- cr/state/committee.go
- cr/state/keyframe.go
- cr/state/keyframe_test.go
- cr/state/proposalmanager.go
- go.mod
- servers/interfaces.go
- test/transaction/crc_proposal_withdraw.lua
- utils/test/test.go
> Adjust the proposal tracking logic

- .travis.yml
- README.md
> Use go mod dependency management system

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- core/types/outputpayload/vote.go
> Votes to eliminate validity checks on candidates

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- cr/state/committee.go
- cr/state/committee_test.go
- cr/state/committeeaction.go
- cr/state/committeerollback_test.go
- cr/state/keyframe.go
a single CRC proposal can only use ten percent of total ELA of the current stage
> a single CRC proposal can only use ten percent of total ELA of the current stage

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- cr/state/committee.go
- cr/state/committeeaction.go
- cr/state/committeerollback_test.go
- cr/state/proposalmanager.go
- cr/state/state.go
> Processing transactions not distinguishes voting period and election period

- LICENSE
> Update main license date

- blockchain/txvalidator.go
- cmd/script/api/payloadtype.go
> Types of Budgets and stage inspection

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
> Check Proposal Withdraw transaction must be CRC committee address

- common/config/config.go
- common/config/settings/settings.go
> Fixed configuration files MaxCommitteeProposalCount position

- docs/jsonrpc_apis.md
- servers/interfaces.go
> Removes the VoteStartHeight field from the ListCRProposalBaseState interface

- .github/workflows/go.yml
> Upgrade actions version

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
> Use the current block height to check whether the proposaled tx is legal

- cr/state/committee.go
Peas enter the commit message for your changes. Lines starting
> Fixed an issue that voting period ended abnormally

- cr/state/committee.go
address amount plus the appropriation amount
> The amount of the session needs to be equal to the CR Expenses

- blockchain/blockvalidator.go
- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- mempool/txpool.go
- pow/service.go
The budget of the proposed transaction of the transaction pool should be counted to verify the budget of the new proposal transaction
>  The budgets of Proposed proposal txns in the pool should be counted

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- cmd/script/api/api.go
- cmd/script/api/payloadtype.go
- cmd/script/script.go
- core/types/payload/crcproposal.go
- cr/state/keyframe.go
- cr/state/proposalmanager.go
- servers/interfaces.go
- test/transaction/crc_change_proposal_owner_tx.lua
> Add replacement proposal leader

- blockchain/txvalidator.go
- blockchain/txvalidator_test.go
- cmd/script/api/payloadtype.go
- cmd/script/script.go
- core/types/payload/crcproposal.go
- cr/state/committee.go
- cr/state/keyframe.go
- cr/state/proposalmanager.go
- servers/interfaces.go
- test/transaction/crc_proposal_tx.lua
Refactor three transaction codes: Secretary-General, Close Proposal, and Change Proposal Owner
> Add change secretary general transaction and refactor three new proposal transaction codes

- blockchain/txvalidator_test.go
- cmd/script/api/payloadtype.go
- cmd/script/api/txtype.go
- cmd/script/script.go
- core/types/attribute.go
- core/types/payload/crcproposal.go
- core/types/transaction_test.go
- test/transaction/crc_change_proposal_owner_tx.lua
> Replace PreviousHash with TargetProposalHash

- cmd/script/script.go
> Fixed repeated newOwnerPublicKey issus

- blockchain/txvalidator.go
- cmd/script/api/api.go
- cmd/script/api/payloadtype.go
- core/types/payload/crdposmanagement.go
- core/types/transaction.go
- core/types/transaction_test.go
- errors/errcode.go
- mempool/conflictfunc.go
- mempool/conflictmanager.go
> Add CR claims DPOS node transactions

- cmd/script/api/payloadtype.go
- cmd/script/script.go
- test/transaction/crc_claims_dpos_node_tx.lua
> Add lua for CR claims DPOS node

- cmd/script/api/payloadtype.go
- cmd/script/script.go
- test/transaction/crc_change_proposal_owner_tx.lua
> Lua add new_owner_private_key

- cmd/script/api/payloadtype.go
- cmd/script/api/txtype.go
- cmd/script/script.go
- test/transaction/crc_claims_dpos_node_tx.lua
> Fixed Lua parameter passing issue

- blockchain/txvalidator.go
- cmd/script/api/payloadtype.go
- core/types/payload/crdposmanagement.go
- core/types/transaction_test.go
> Fixing serialization errors and remove dpos management type

- mempool/conflictmanager.go
> Fixed slotCRManagementDID call error

- blockchain/txvalidator.go
- cmd/script/api/payloadtype.go
- cmd/script/script.go
- test/transaction/crc_claims_dpos_node_tx.lua
> Add check CR claim DPOS Management Signature

- blockchain/txvalidator.go
- cr/state/committee.go
- cr/state/keyframe.go
- mempool/conflictfunc.go
- mempool/conflictmanager.go
- servers/httpjsonrpc/server.go
- servers/interfaces.go
Add slotCRCSecretaryGeneral to avoid change secretary general tx duplication
> Add slotCRCSecretaryGeneral to avoid  tx duplication

- cr/state/keyframe.go
- dpos/manager/dposmanager.go
- dpos/state/arbitrators.go
- dpos/state/state.go
and fix when cr claim dpos started cr reward not been destroyed
Using owner public key instead of node public key
Fix copy problem
> Fix cr member not inactive when maxinactiveround reach

- dpos/state/arbitrators.go
- dpos/state/state.go
period, if it does not claim DPOS node
> CR member will not be set to Inactive in claim dpos node

- cr/state/committee.go
- cr/state/state.go
- docs/jsonrpc_apis.md
- servers/interfaces.go
> Add the field depositAmount to the RPC interface

- common/config/config.go
- common/config/params.go
- common/config/settings/settings.go
- go.mod
- servers/httpjsonrpc/server.go
> Add a cross-domain request switch

- .github/workflows/go.yml
- .gitignore
- Makefile
- blockchain/blockchain.go
- core/checkpoint/manager.go
- dpos/state/keyframe.go
- elanet/server.go
- p2p/connmgr/connmanager.go
- p2p/connmgr/connmanager_test.go
> Fix data contention in block synchronization

- dpos/state/arbitrators.go
> Fixed distributeWithNormalArbitratorsV2 logic errors

- docs/release-notes/release-notes-0.7.0.md
> doc: Add historical release notes for 0.7.0

- .gitignore
- LICENSE
- blockchain/validation.go
- blockchain/validation_test.go
- crypto/schnorr.go
- vm/opcode.go
> Move schnorr to the crypto package 

- account/account.go
- blockchain/validation_test.go
- cmd/script/api/accounttype.go
- cmd/script/api/api.go
- cmd/script/api/txtype.go
- cmd/script/script.go
- mempool/txpool.go
- test/transaction/normal_schnorr_tx.lua
> ela-cli: Support lua build Schnorr signature transactions

- go.mod
- test/unit/txvalidator_test.go
> feat(dpos2.0): add check stake transaction test case

- core/transaction/registerproducertransaction.go
- core/transaction/returndepositcointransaction.go
- core/transaction/txdeserialize_test.go
- core/transaction/updateproducertransaction.go
- dpos/state/state.go
allow producer to withdraw deposit coin when reached the stakeUntil height
> feat(dpos2.0): allow producer to withdraw deposit coin correctly

- core/transaction/voting.go
This reverts commit 31e3444fadea2fa6068a9be8c5fb152e556512cf.
> Revert "fix(dpos2.0): mdofiy to check total votes correctly"

- core/types/payload/unstakerealwithdraw.go
- dpos/state/keyframe.go
- servers/httpjsonrpc/server.go
- servers/interfaces.go
fix(dpos2.0): change len(p.UnstakeRealWithdraw) from VarUint64 to VarUint
>     fix(dpos2.0): add getdposv2info rpc and fix UnstakeRealWithdrawPayload   Deserialize panic

- dpos/state/arbitrators.go
- dpos/state/state.go
fix(dpos2.0): DPosV2 sort change from DposV2Votes() into GetTotalDPoSV2VoteRights()
>  fix(dpos2.0): DPosV2 sort change from DposV2Votes() into GetTotalDPoSV2VoteRights()

- core/transaction/updateproducertransaction.go
> fix(dpos2.0): remove producer node key can not be owner key check

- core/transaction/updateproducertransaction.go
- core/types/common/transaction.go
>  fix(dpos2.0): only after DPoSV2StartHeight DPoSV1 can update to DPoSV1V2

- .github/workflows/go.yml
- common/config/config.go
- go.mod
- main.go
- utils/common.go
> feat(dpos2.0): adding performance monitoring

- benchmark/sync/synctobestheight_test.go
- main.go
- utils/common.go
> fix(dpos2.0): pprof goes into the tool function

- docs/config.json.md
> feat(dpos2.0): update config sample

- test/transaction/register_cr_schnorr_tx.lua
> feat(dpos2.0): add register cr schnorr tx.lua

- account/account.go
> fix(dpos2.0): fix schnorr account struct SumPublicKey type to byte

- cr/state/committee.go
- cr/state/committeeaction.go
- cr/state/keyframe.go
> feat(dpos2.0): refactor logic of inactive CR member by withdraw txs

- cmd/wallet/transaction.go
- cmd/wallet/vote.go
> feat(dpos2.0): ela-cli support create stake tx

- test/unit/txvalidator_test.go
> feat(dpos2.0): add dposv2 testcase for SpecialContextCheck

- cmd/script/api/api.go
- cmd/script/api/payloadtype.go
- core/transaction/activateproducertransaction.go
- core/transaction/cancelproducertransaction.go
- core/transaction/registerproducertransaction.go
- core/transaction/updateproducertransaction.go
- core/types/payload/activateproducer.go
- core/types/payload/processproducer.go
- core/types/payload/producerinfo.go
- test/transaction/update_producer_v2_schnorr_tx.lua
Producer transaction add schnorr support
> producer trancation add schnorr support

- common/config/config.go
- main.go
> fix(nft): add missing password parameters

- common/config/config.go
- common/config/settings/settings.go
- dpos/arbitrator.go
- dpos/network.go
- main.go
> fix(nft): fix SignTolerance time duration parameter error

- docs/release-notes/release-notes-0.3.4.md
- docs/release-notes/release-notes-0.4.0.md
- docs/release-notes/release-notes-0.9.0.md
- docs/release-notes/release-notes-0.9.9.md
This pull request contains changes to improve clarity, correctness and structure.
> fix: typos in documentation files
